# GitHub Actions workflow to deploy to Azure Functions and run Playwright tests
name: Deploy and Test Azure Function

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  playwright-test:
    needs: build-and-deploy
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test

          service-connection: ${{ secrets.AZURE_PLAYWRIGHT_SERVICE_CONNECTION }}
          test-folder: tests
          app-url: ${{ secrets.AZURE_FUNCTIONAPP_URL }}