# GitHub Actions workflow to deploy to Azure Functions and run Playwright tests
name: Deploy and Test Azure Function


on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: # Required when using Microsoft Entra ID to authenticate
  id-token: write
  contents: read


jobs:
  build-and-deploy:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true

  playwright-test:
    needs: build-and-deploy
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3

      - name: Login to Azure with AzPowershell (enableAzPSSession true)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} # GitHub Open ID connect values copied in previous steps
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Install dependencies
        working-directory: tests
        run: npm ci

      - name: Run Playwright tests
        working-directory: tests
        env:
          # Regional endpoint for Microsoft Playwright Testing
          PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
          AZURE_FUNCTIONAPP_URL: ${{ secrets.AZURE_FUNCTIONAPP_URL }}
        run: npx playwright test -c playwright.service.config.ts --workers=20

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright-report/ 
          retention-days: 10
